'use strict';
const calc = require('./calc');
const R = require('./render');
const { pairSlug, machineName, QUANT_ORDER } = require('./pages');
const { esc, gib, ctxLabel, pill } = R;

/* ───────────────── "best model for N GB" — one per memory tier ───────────────── */

function ramGuide(ramGb, ctx) {
  const { models, machines } = ctx;
  const tier = machines.filter((h) => h.ram_gb === ramGb).sort((a, b) => b.bandwidth_gbps - a.bandwidth_gbps);
  const rep = tier[0];
  const scored = models
    .map((m) => ({ m, f: calc.fit(m, rep) }))
    .filter((x) => x.f.verdict.key === 'comfortable')
    .sort((a, b) => b.m.params_b - a.m.params_b);

  const pick = (pred) => scored.find(pred) || null;
  const picks = [
    { role: 'Best all-round', why: 'the largest general-purpose model that still leaves room to work', x: pick((s) => !s.m.tags.includes('coding')) },
    { role: 'Best for coding', why: 'trained specifically on code, and worth the swap if that is your workload', x: pick((s) => s.m.tags.includes('coding')) },
    { role: 'Best for reasoning', why: 'thinks before answering; slower per question, better on hard ones', x: pick((s) => s.m.tags.includes('reasoning')) },
    { role: 'Fastest usable', why: 'when latency matters more than depth — voice assistants, autocomplete, agents', x: scored.slice().sort((a, b) => b.f.tokensPerSecond - a.f.tokensPerSecond)[0] },
  ].filter((p) => p.x);

  const title = `Best local LLM for a ${ramGb}GB Mac (${new Date().getFullYear()})`;
  const description = `A ${ramGb}GB Mac has about ${gib(calc.usableGiB(ramGb))} for a model. Here is the largest thing that fits, the fastest thing that is worth running, and what to avoid.`;

  const body = `
<div class="crumbs"><a href="../../">Home</a> › <a href="../">Guides</a> › ${ramGb}GB</div>
<h1>The best local LLM for a ${ramGb}GB Mac</h1>
<p class="sub">${esc(tier.map(machineName).join(', '))} — about ${gib(calc.usableGiB(ramGb))} usable once macOS has taken its share.</p>

<p>Unified memory is the whole game on Apple Silicon. Your ${ramGb}GB is shared between macOS, your apps and the model, so the honest budget is closer to <strong>${gib(calc.usableGiB(ramGb))}</strong> than to ${ramGb}. Everything below is sized against that number, at Q4_K_M with an 8K context.</p>

<h2>The picks</h2>
${picks.map((p) => `
<h3>${esc(p.role)}: ${esc(p.x.m.name)}</h3>
<p>${esc(p.why.charAt(0).toUpperCase() + p.why.slice(1))}. It loads in <strong>${gib(p.x.f.totalGiB)}</strong> and generates around <strong>${p.x.f.tokensPerSecond.toFixed(0)} tokens/sec</strong> on an ${esc(machineName(rep))}. <a href="../../can/${pairSlug(p.x.m, rep)}/">Full breakdown →</a></p>
`).join('')}

<h2>Everything that fits in ${ramGb}GB</h2>
${R.table(
  ['Model', { label: 'Params', num: true }, { label: 'Loaded', num: true }, { label: 'Tok/s', num: true }, { label: 'Max ctx', num: true }],
  scored.map((s) => [
    `<td><a href="../../models/${s.m.id}/">${esc(s.m.name)}</a></td>`,
    `<td class="num">${s.m.params_b}B</td>`,
    `<td class="num">${gib(s.f.totalGiB)}</td>`,
    `<td class="num">${s.f.tokensPerSecond.toFixed(0)}</td>`,
    `<td class="num">${ctxLabel(calc.maxContext(s.m, rep))}</td>`,
  ])
)}

<h2>What does not fit</h2>
${R.table(
  ['Model', { label: 'Needs', num: true }, { label: 'Short by', num: true }],
  models.map((m) => ({ m, f: calc.fit(m, rep) })).filter((x) => x.f.verdict.key === 'no').sort((a, b) => a.f.totalGiB - b.f.totalGiB).slice(0, 10).map((x) => [
    `<td><a href="../../can/${pairSlug(x.m, rep)}/">${esc(x.m.name)}</a></td>`,
    `<td class="num">${gib(x.f.totalGiB)}</td>`,
    `<td class="num">${gib(x.f.totalGiB - x.f.usableGiB)}</td>`,
  ])
)}
<p>A model that is a gigabyte or two over can often be rescued by dropping to Q3_K_M or quantising the KV cache. Anything further over than that is better solved by picking a smaller model — a 14B at Q4 beats a 32B at Q2 on almost every task.</p>

${R.affiliateBlock(ramGb <= 24 ? 'upgrade_ram' : 'storage')}

<h2>Machines in this tier</h2>
<div class="grid">${tier.map((h) => `<a class="card" href="../../macs/${h.id}/"><div class="t">${esc(machineName(h))}</div><div class="d">${h.bandwidth_gbps} GB/s · ${esc(h.products[0])}</div></a>`).join('')}</div>
`;
  return { path: `guides/best-llm-for-${ramGb}gb-mac/index.html`, html: R.page({ title, description, canonical: `/guides/best-llm-for-${ramGb}gb-mac/`, body, depth: 2 }), priority: 0.9 };
}

/* ───────────────────────────── evergreen explainers ───────────────────────────── */

function methodPage(ctx) {
  const body = `
<div class="crumbs"><a href="../">Home</a> › Method</div>
<h1>How these numbers are calculated</h1>
<p class="sub">Every figure on this site is arithmetic on published specifications. None of it is generated by a language model, and none of it is a benchmark.</p>

<h2>Weights</h2>
<p>Weight memory is parameter count times bits per parameter. The bits per parameter for each quantisation are the effective GGUF rates, which are slightly above the nominal value because embedding and output tensors are usually kept at higher precision:</p>
${R.table(['Quantisation', { label: 'Bits/param', num: true }], QUANT_ORDER.map((q) => [`<td>${esc(calc.QUANTS[q].label)}</td>`, `<td class="num">${calc.QUANTS[q].bits}</td>`]))}
<p>So Llama 3.1 8B at Q4_K_M is 8.03 × 10⁹ × 4.9 ÷ 8 = ${gib(calc.weightsGiB(8.03))}, which matches the published file size.</p>

<h2>KV cache</h2>
<p>The KV cache stores one key and one value vector per layer per token. Its size is <code>2 × layers × kv_heads × head_dim × 2 bytes</code> per token, which is a fixed property of the architecture. Grouped-query attention is why a 7B Qwen has a far smaller cache than a 9B Gemma.</p>
<p>Multiply that per-token figure by your context length. At 128K context the cache can be larger than the weights.</p>

<h2>Runtime overhead</h2>
<p>Compute buffers, activations and the inference process itself. Modelled as <code>0.5 GiB + 5% of weights + 0.3 GiB per 8K of context</code> — a reasonable approximation of what llama.cpp and MLX actually allocate.</p>

<h2>Usable memory</h2>
<p>macOS, the window server and your open apps need memory too, and Metal applies a default wired-memory limit. We reserve 15% of unified memory, floored at 3 GiB and capped at 16 GiB. On a 16GB Mac that leaves ${gib(calc.usableGiB(16))}; on a 64GB Mac, ${gib(calc.usableGiB(64))}.</p>
<p>You can push past this with <code>sudo sysctl iogpu.wired_limit_mb=N</code>, which is why pages marked "tight" are often still worth trying.</p>

<h2>Token speed</h2>
<p>Generating a token requires reading every active weight from memory once. That makes generation <em>memory-bandwidth bound</em>, not compute bound — which is why an M4 Max at 546 GB/s is roughly four times faster than an M4 at 120 GB/s on the same model, despite a much smaller gap in GPU cores.</p>
<p>The estimate is <code>bandwidth ÷ active weight size × efficiency</code>, with efficiency at 0.80 for dense models and 0.50 for mixture-of-experts models, whose sparse gather patterns use bandwidth less effectively.</p>

<h2>What this does not model</h2>
<ul>
<li><strong>Prompt processing speed</strong>, which is compute bound and depends on GPU core count.</li>
<li><strong>Thermal throttling.</strong> A MacBook Air under sustained load will fall below these numbers; a Mac Studio will not.</li>
<li><strong>Quality.</strong> Fitting is not the same as being good. A model that barely fits at Q2 is usually worse than a smaller one at Q4.</li>
<li><strong>Speculative decoding, batching or draft models</strong>, all of which can beat these figures.</li>
</ul>
<p>Treat everything here as a well-founded estimate that tells you what to try, not a benchmark result. The calculation lives in <code>lib/calc.js</code> in the repository and is about a hundred lines — read it if you want to check the assumptions.</p>
`;
  return { path: 'method/index.html', html: R.page({ title: 'How we calculate local LLM memory requirements on Apple Silicon', description: 'The full arithmetic behind every number on this site: weight sizes, KV cache, runtime overhead, usable unified memory and bandwidth-bound token speed.', canonical: '/method/', body, depth: 1 }), priority: 0.6 };
}

function guidesIndex(ctx, ramTiers) {
  const body = `<div class="crumbs"><a href="../">Home</a> › Guides</div>
<h1>Guides</h1>
<p class="sub">Start with your memory tier — it is the only spec that decides what you can run.</p>
<div class="grid">${ramTiers.map((r) => `<a class="card" href="best-llm-for-${r}gb-mac/"><div class="t">Best LLM for a ${r}GB Mac</div><div class="d">${ctx.models.filter((m) => calc.fit(m, { ram_gb: r, bandwidth_gbps: 100 }).verdict.key === 'comfortable').length} models fit</div></a>`).join('')}</div>
<h2>Reference</h2>
<div class="grid">
<a class="card" href="../method/"><div class="t">How the numbers work</div><div class="d">The arithmetic behind every figure</div></a>
<a class="card" href="../models/"><div class="t">All models</div><div class="d">Sizes and requirements</div></a>
<a class="card" href="../macs/"><div class="t">All Macs</div><div class="d">What each configuration runs</div></a>
</div>`;
  return { path: 'guides/index.html', html: R.page({ title: 'Local AI guides for Apple Silicon Macs', description: 'Pick the right local LLM for your Mac, by memory tier.', canonical: '/guides/', body, depth: 1 }), priority: 0.8 };
}

function homePage(ctx, ramTiers) {
  const { models, machines } = ctx;
  const popular = [
    ['llama-3-1-8b', 'm4-16gb'], ['llama-3-3-70b', 'm4-max-64gb'], ['qwen2-5-coder-32b', 'm4-pro-48gb'],
    ['gpt-oss-20b', 'm4-24gb'], ['gemma-3-27b', 'm4-max-36gb'], ['qwen3-32b', 'm4-pro-48gb'],
    ['r1-distill-qwen-14b', 'm4-24gb'], ['llama-3-2-3b', 'm1-8gb'], ['mistral-small-24b', 'm4-pro-24gb'],
  ].map(([mi, hi]) => ({ m: models.find((x) => x.id === mi), h: machines.find((x) => x.id === hi) }))
   .filter((x) => x.m && x.h)
   .map((x) => ({ ...x, f: calc.fit(x.m, x.h) }));

  const body = `
<h1>Which AI models actually run on your Mac?</h1>
<p class="sub">Unified memory decides everything. Pick your Mac, see what fits — with the arithmetic shown, not guessed.</p>

<h2>Start with your memory</h2>
<div class="grid">${ramTiers.map((r) => `<a class="card" href="guides/best-llm-for-${r}gb-mac/"><div class="t">${r} GB</div><div class="d">${gib(calc.usableGiB(r))} usable for a model</div></a>`).join('')}</div>

<h2>Frequently checked</h2>
${R.table(
  ['Question', 'Answer', { label: 'Tok/s', num: true }],
  popular.map((p) => [
    `<td><a href="can/${pairSlug(p.m, p.h)}/">${esc(p.m.name)} on ${esc(machineName(p.h))}</a></td>`,
    `<td>${pill(p.f)}</td>`,
    `<td class="num">${p.f.tokensPerSecond.toFixed(0)}</td>`,
  ])
)}

<h2>Why memory, and not the GPU</h2>
<p>Generating one token means reading every active parameter out of memory. That makes local inference bandwidth bound, so the two numbers that decide your experience are <strong>how much unified memory you have</strong> (what fits) and <strong>how fast it is</strong> (how quickly it runs). GPU core count barely moves the needle for chat.</p>
<p>A Mac mini M4 with 24GB will run an 8B model at reading speed. A MacBook Pro M4 Max with 128GB will run a 70B model at the same speed, because its memory is four and a half times faster. Neither can be upgraded after purchase, which is why the configuration you buy is the decision that matters.</p>

<div class="grid">
<a class="card" href="models/"><div class="t">Browse ${models.length} models</div><div class="d">Llama, Qwen, Gemma, Mistral, DeepSeek, Phi, gpt-oss</div></a>
<a class="card" href="macs/"><div class="t">Browse ${machines.length} Mac configs</div><div class="d">M1 through M4 Max and M3 Ultra</div></a>
<a class="card" href="method/"><div class="t">How we calculate it</div><div class="d">Every formula, shown in full</div></a>
</div>

${R.affiliateBlock('upgrade_ram')}
`;
  return { path: 'index.html', html: R.page({ title: 'Can It Run? — Which AI models run on your Mac', description: 'Memory requirements and speed estimates for running local LLMs on Apple Silicon. Every number computed from published specs, with the arithmetic shown.', canonical: '/', body, depth: 0 }), priority: 1.0 };
}

module.exports = { ramGuide, methodPage, guidesIndex, homePage };
