#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# This wizard configures the live site, so it must run from the repo.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
ENV_FILE="$REPO/.env"

SITE_URL=$(node -e "process.stdout.write(require('./data/site.json').baseUrl)")

banner "Can It Run? — monetisation and indexing setup"

# ── 1. Amazon Associates ──────────────────────────────────────────────────
stage "Amazon Associates"
say "This is the only thing standing between the site and revenue."
say "Approval needs a live site with real content, which you now have."
printf '\n'
open_url "https://affiliate-program.amazon.com/"
step "Click 'Sign up' and log in with your normal Amazon account."
step "Account info: your name and address."
step "Website list: paste this exact URL —"
note "    $SITE_URL"
step "Profile: pick a store ID (this becomes your tracking tag)."
step "Say your site is about consumer electronics / computers."
step "Traffic question: answer honestly — SEO / search traffic."
step "Payment and tax details can be filled in later."
printf '\n'
warn "Amazon requires 3 qualifying sales within 180 days or the account closes."
note "That clock starts at approval, not today. If the site has no traffic yet,"
note "it is reasonable to wait and apply once Search Console shows impressions."
printf '\n'
if confirm "Do you have your tracking tag now (looks like yourname-20)?"; then
  ask AMAZON_TAG "Paste your Associates tracking tag:"
  if [[ -n "${AMAZON_TAG:-}" ]]; then
    write_env AMAZON_TAG "$AMAZON_TAG"
    node scripts/set-affiliate-tag.js "$AMAZON_TAG" || warn "tag rejected; run scripts/set-affiliate-tag.js by hand"
  fi
else
  SKIPPED+=("Amazon tag — re-run this wizard, or: node scripts/set-affiliate-tag.js <tag>")
  note "Fine. The site keeps rendering plain links until a tag is set."
  pause
fi

# ── 2. Google Search Console: verification token ──────────────────────────
stage "Google Search Console — get the token"
say "Nothing ranks on Google until Google knows the site exists."
printf '\n'
open_url "https://search.google.com/search-console"
step "Log in with your Google account."
step "Click the property dropdown (top left) → 'Add property'."
warn "Choose the 'URL prefix' box on the RIGHT, not 'Domain' on the left."
note "Domain properties need DNS records, which github.io will not give you."
step "Paste this exact URL, including the trailing slash —"
note "    $SITE_URL/"
step "Click Continue. A list of verification methods appears."
step "Expand 'HTML tag'. You will see a meta tag like:"
note "    <meta name=\"google-site-verification\" content=\"AbC123...\" />"
step "Copy ONLY the content value — the part inside the quotes."
printf '\n'
ask GOOGLE_VERIFICATION "Paste the content value:"
if [[ -n "${GOOGLE_VERIFICATION:-}" ]]; then
  write_env GOOGLE_VERIFICATION "$GOOGLE_VERIFICATION"
  node -e "
    const fs=require('fs'),p='data/site.json',s=JSON.parse(fs.readFileSync(p));
    s.googleVerification=process.argv[1];
    fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');
    console.log('  ✓ wrote googleVerification into data/site.json');
  " "$GOOGLE_VERIFICATION"
  note "Leave the Search Console tab open — you click Verify in the next stage."
else
  SKIPPED+=("Google Search Console verification")
fi
pause

# ── 3. Publish the token, then verify and submit the sitemap ──────────────
stage "Google Search Console — publish, verify, submit"
if [[ -z "${GOOGLE_VERIFICATION:-}" ]]; then
  note "No token captured, so there is nothing to publish. Skipping."
  pause
else
  say "The meta tag has to be live on the site before Google will accept it."
  printf '\n'
  say "Rebuilding all 1,137 pages with the tag and pushing..."
  node build.js
  git add -A data docs
  git commit -q -m "Add Google Search Console verification tag" || note "nothing to commit"
  git push -q origin main && printf '  %s✓ pushed%s\n' "$GREEN" "$RESET"
  printf '\n'
  say "Waiting for GitHub Pages to serve the new build..."
  for _ in $(seq 1 60); do
    if curl -s "$SITE_URL/" | grep -q "$GOOGLE_VERIFICATION"; then
      printf '  %s✓ verification tag is live%s\n' "$GREEN" "$RESET"; break
    fi
    sleep 10
  done
  printf '\n'
  step "Switch back to the Search Console tab and click VERIFY."
  pause "Press Enter once Google says verified."
  printf '\n'
  step "Now, in the left sidebar, click 'Sitemaps'."
  step "Under 'Add a new sitemap', enter exactly:  sitemap.xml"
  step "Click Submit. It should report Success and 1,137 discovered URLs."
  printf '\n'
  note "Indexing takes days to weeks. Impressions show up in Performance first."
  pause
fi

# ── 4. Bing Webmaster Tools (optional) ────────────────────────────────────
stage "Bing Webmaster Tools (optional)"
say "IndexNow already pushed all 1,137 URLs to Bing — that part is done."
say "Adding the site here only buys you Bing's analytics and crawl reports."
printf '\n'
if confirm "Set up Bing Webmaster Tools too?"; then
  open_url "https://www.bing.com/webmasters/"
  step "Sign in, then choose 'Import from Google Search Console' if offered —"
  note "that is by far the fastest route and skips verification entirely."
  step "Otherwise click 'Add site manually' and enter:  $SITE_URL/"
  step "Pick the 'HTML Meta Tag' option and copy the content value."
  printf '\n'
  ask BING_VERIFICATION "Paste the content value (or press Enter if you imported):"
  if [[ -n "${BING_VERIFICATION:-}" ]]; then
    write_env BING_VERIFICATION "$BING_VERIFICATION"
    node -e "
      const fs=require('fs'),p='data/site.json',s=JSON.parse(fs.readFileSync(p));
      s.bingVerification=process.argv[1];
      fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');
      console.log('  ✓ wrote bingVerification into data/site.json');
    " "$BING_VERIFICATION"
    node build.js
    git add -A data docs
    git commit -q -m "Add Bing Webmaster verification tag" || true
    git push -q origin main && printf '  %s✓ pushed%s\n' "$GREEN" "$RESET"
    note "Wait a minute for Pages to rebuild, then click Verify in Bing."
  fi
  pause
else
  note "Skipped. IndexNow keeps working regardless."
  pause
fi

# ── 5. Custom domain (optional, the only thing that costs money) ──────────
stage "Custom domain (optional)"
say "A real domain reads better than github.io and is the only line item here."
say "Roughly \$12/year. Everything works without it."
printf '\n'
if confirm "Point a custom domain at the site now?"; then
  say "Buy a domain first if you have not — Cloudflare and Namecheap are fine."
  printf '\n'
  ask CUSTOM_DOMAIN "Enter the domain (e.g. canitrun.ai, no https://):"
  if [[ -n "${CUSTOM_DOMAIN:-}" ]]; then
    write_env CUSTOM_DOMAIN "$CUSTOM_DOMAIN"
    printf '\n'
    step "In your registrar's DNS panel, create four A records for the apex (@):"
    note "    185.199.108.153"
    note "    185.199.109.153"
    note "    185.199.110.153"
    note "    185.199.111.153"
    step "And one CNAME record: www → mckademumbower40-ship-it.github.io"
    printf '\n'
    pause "Press Enter once the DNS records are saved."

    node -e "
      const fs=require('fs'),p='data/site.json',s=JSON.parse(fs.readFileSync(p));
      s.baseUrl='https://'+process.argv[1];
      fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');
      console.log('  ✓ baseUrl now https://'+process.argv[1]);
    " "$CUSTOM_DOMAIN"

    # Moving domain invalidates the old IndexNow key location.
    say "Re-issuing the IndexNow key for the new domain..."
    node -e "
      const fs=require('fs'),p='data/site.json',s=JSON.parse(fs.readFileSync(p));
      const old=s.indexNowKey; s.indexNowKey='';
      fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');
      if(old) try{fs.unlinkSync('static/'+old+'.txt')}catch{}
    "
    node scripts/indexnow.js --init

    node build.js
    git add -A data docs static
    git commit -q -m "Point site at $CUSTOM_DOMAIN" || true
    git push -q origin main && printf '  %s✓ pushed (CNAME file generated automatically)%s\n' "$GREEN" "$RESET"
    printf '\n'
    warn "DNS can take up to 24 hours. Then in the repo Settings → Pages,"
    warn "tick 'Enforce HTTPS' once the certificate is issued."
    warn "You must also add the new domain as a fresh Search Console property."
    SKIPPED+=("Search Console property for https://$CUSTOM_DOMAIN")
    SKIPPED+=("IndexNow re-submission once DNS resolves: node scripts/indexnow.js")
  fi
  pause
else
  note "Skipped. github.io works perfectly well."
  pause
fi

finish
